language: node_js
dist: trusty
node_js:
  - '10'
install:
  - npm install
env:
  - MOZ_HEADLESS=1
addons:
  firefox: latest
script:
  - npm run build:spec
  - npm test -- -sc
after_success: npm run coveralls
