language: node_js
node_js:
  - '6'
install: npm install; npm run cjs
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 2
script: npm test -- -b firefox -sc & npm test -- -b firefox -sr cjs
after_success: npm run coveralls
