language: node_js
node_js:
  - '5'
install:
  - npm install
  - npm run es5
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 2
script:
  - npm test -- -b firefox -sc
  - npm test -- -b firefox -sr es5
after_success: npm run coveralls
