language: node_js
node_js:
  - '6'
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
install: npm install
script: npm run test -- -b firefox -sc
after_success: npm run coveralls
