language: node_js
node_js:
  - '6'
install: npm install
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm run build:polyfills
  - sleep 2
script: npm run test -- -b firefox -sc
after_success: npm run coveralls
